###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

## Preprocessor settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

## Jekyll Serve
port: 4000

## Output
siteurl:                    ## Optional 
baseurl: /intern
destination: docs


title: CDA Orga
keywords: jekyll, cda 
author: Matthew Elsom
description: CDA Orgabereich
language: de
styles: assets/css/cda-orga.css
favicon: assets/images/favicon.ico

## Generates Style Guide Shell Styles
## Enable to change the style guide shell stylesheet.
#sass: 
#  sass_dir: styleguide/_scss
#  style: :compressed


## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
sass:
  sass_dir: assets/_scss 
  style: compressed

collections:
  news:
    output: false